### ISSUE TITLE
voip issue 

### ISSUE THREAD

**Issue by sousou63** [dxura/darkrp#43]
Idk what voip system nicked use but we made some test in multiplayer and the voip is kind of weird, it's very laggy maybe we should switch to the default voip system

**Comment by jusvit** [comment]
Are you sure it wasn't latency related? We were using it fine.

**Comment by sousou63** [comment]
I was the host, for me, it went pretty well, but the other players were having a lot of trouble (apparently there was a lot of crackling and lag). Starting with 7-8 players, even I, as the host, started to hear it. This will require more testing, but I'm leaving this here for later.
